# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 736a69d7f89721da542d355d14f93d76f3f26cbc410d753d98791fb685bebe517c0c5fc7ba80cd54591b5e581e831d53ae9bb130228b83c6f71fb17ba49e9f0c

test:
  secret_key_base: cb269071f80a16cc88510c29115fcee18a00aec9ea827504177004015caec8c822a87bdc32864757891b897c1a5db8c5c6bcb46a64f6c0195506a72e34afeed6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
